# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'acq4/util/imaging/imaging_template.ui',
# licensing of 'acq4/util/imaging/imaging_template.ui' applies.
#
# Created: Tue Jun 25 14:49:02 2019
#      by: pyside2-uic  running on PySide2 5.9.0~a1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(187, 247)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 2, 0, 1, 1)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 1, 0, 1, 2)
        self.acqBtnLayout = QtWidgets.QGridLayout()
        self.acqBtnLayout.setObjectName("acqBtnLayout")
        self.acquireFrameBtn = QtWidgets.QPushButton(Form)
        self.acquireFrameBtn.setObjectName("acquireFrameBtn")
        self.acqBtnLayout.addWidget(self.acquireFrameBtn, 0, 0, 1, 1)
        self.acquireVideoBtn = QtWidgets.QPushButton(Form)
        self.acquireVideoBtn.setCheckable(True)
        self.acquireVideoBtn.setObjectName("acquireVideoBtn")
        self.acqBtnLayout.addWidget(self.acquireVideoBtn, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.acqBtnLayout, 0, 0, 1, 2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 7, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 4, 0, 1, 1)
        self.stackSizeLabel = QtWidgets.QLabel(Form)
        self.stackSizeLabel.setObjectName("stackSizeLabel")
        self.gridLayout.addWidget(self.stackSizeLabel, 4, 1, 1, 2)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 6, 0, 1, 1)
        self.fpsLabel = ValueLabel(Form)
        self.fpsLabel.setObjectName("fpsLabel")
        self.gridLayout.addWidget(self.fpsLabel, 6, 1, 1, 1)
        self.recordXframesSpin = QtWidgets.QSpinBox(Form)
        self.recordXframesSpin.setEnabled(True)
        self.recordXframesSpin.setMinimum(1)
        self.recordXframesSpin.setMaximum(1000000)
        self.recordXframesSpin.setProperty("value", 100)
        self.recordXframesSpin.setObjectName("recordXframesSpin")
        self.gridLayout.addWidget(self.recordXframesSpin, 3, 1, 1, 2)
        self.recordXframesCheck = QtWidgets.QCheckBox(Form)
        self.recordXframesCheck.setObjectName("recordXframesCheck")
        self.gridLayout.addWidget(self.recordXframesCheck, 3, 0, 1, 1)
        self.recordStackBtn = QtWidgets.QPushButton(Form)
        self.recordStackBtn.setCheckable(True)
        self.recordStackBtn.setFlat(False)
        self.recordStackBtn.setObjectName("recordStackBtn")
        self.gridLayout.addWidget(self.recordStackBtn, 2, 0, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 5, 0, 1, 1)
        self.displayPercentLabel = ValueLabel(Form)
        self.displayPercentLabel.setObjectName("displayPercentLabel")
        self.gridLayout.addWidget(self.displayPercentLabel, 7, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 1, 0, 1, 1)
        self.displayFpsLabel = ValueLabel(Form)
        self.displayFpsLabel.setObjectName("displayFpsLabel")
        self.gridLayout.addWidget(self.displayFpsLabel, 7, 1, 1, 1)
        self.clearPinnedFramesBtn = QtWidgets.QPushButton(Form)
        self.clearPinnedFramesBtn.setObjectName("clearPinnedFramesBtn")
        self.gridLayout.addWidget(self.clearPinnedFramesBtn, 0, 1, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 5, 0, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.saveFrameBtn = FeedbackButton(Form)
        self.saveFrameBtn.setObjectName("saveFrameBtn")
        self.horizontalLayout.addWidget(self.saveFrameBtn)
        self.linkSavePinBtn = QtWidgets.QPushButton(Form)
        self.linkSavePinBtn.setMaximumSize(QtCore.QSize(20, 16777215))
        self.linkSavePinBtn.setCheckable(True)
        self.linkSavePinBtn.setObjectName("linkSavePinBtn")
        self.horizontalLayout.addWidget(self.linkSavePinBtn)
        self.pinFrameBtn = QtWidgets.QPushButton(Form)
        self.pinFrameBtn.setObjectName("pinFrameBtn")
        self.horizontalLayout.addWidget(self.pinFrameBtn)
        self.gridLayout_2.addLayout(self.horizontalLayout, 3, 0, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.acquireFrameBtn.setText(QtWidgets.QApplication.translate("Form", "Acquire Frame", None, -1))
        self.acquireVideoBtn.setToolTip(QtWidgets.QApplication.translate("Form", "Start/stop camera acquisition.\n"
"In general, this can just stay on always.", None, -1))
        self.acquireVideoBtn.setText(QtWidgets.QApplication.translate("Form", "Acquire Video", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("Form", "Displaying:", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("Form", "Stack Size:", None, -1))
        self.stackSizeLabel.setText(QtWidgets.QApplication.translate("Form", "0 frames", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Form", "Acquiring:", None, -1))
        self.fpsLabel.setText(QtWidgets.QApplication.translate("Form", "0 fps", None, -1))
        self.recordXframesSpin.setSuffix(QtWidgets.QApplication.translate("Form", " frames", None, -1))
        self.recordXframesCheck.setText(QtWidgets.QApplication.translate("Form", "Stack Limit", None, -1))
        self.recordStackBtn.setToolTip(QtWidgets.QApplication.translate("Form", "Start/stop recording frames as they are acquired. \n"
"Frames are written to the current storage directory set in \n"
"the data manager window.", None, -1))
        self.recordStackBtn.setText(QtWidgets.QApplication.translate("Form", "Record Stack", None, -1))
        self.displayPercentLabel.setText(QtWidgets.QApplication.translate("Form", "(0%)", None, -1))
        self.displayFpsLabel.setText(QtWidgets.QApplication.translate("Form", "0 fps", None, -1))
        self.clearPinnedFramesBtn.setText(QtWidgets.QApplication.translate("Form", "Clear Pinned Frames", None, -1))
        self.saveFrameBtn.setToolTip(QtWidgets.QApplication.translate("Form", "Store the last acquired frame to disk", None, -1))
        self.saveFrameBtn.setText(QtWidgets.QApplication.translate("Form", "Save Frame", None, -1))
        self.linkSavePinBtn.setToolTip(QtWidgets.QApplication.translate("Form", "Link the Save Frame and Pin Frame buttons so that clicking either button performs both functions", None, -1))
        self.linkSavePinBtn.setText(QtWidgets.QApplication.translate("Form", "<>", None, -1))
        self.pinFrameBtn.setToolTip(QtWidgets.QApplication.translate("Form", "Pin the last acquired frame to the view background", None, -1))
        self.pinFrameBtn.setText(QtWidgets.QApplication.translate("Form", "Pin Frame", None, -1))

from acq4.pyqtgraph import ValueLabel, FeedbackButton
